[package]
name = "yaml-include"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
base64 = "0.21.2"
clap = { version = "4.3.0", features = ["derive"] }
regex = "1.8.3"
serde_yaml = "0.9.21"
yaml-rust = "0.4.5"
